[package]
name = "bls_sigs_test"
version = "0.1.0"
authors = ["kwantam <kwantam@gmail.com>"]
license = "MIT"

[dependencies]
bls_sigs_ref-rs = { path = "../" }
pairing-plus = { version = "0.17.0", git = "https://github.com/algorand/pairing-plus", branch = "release-0.17.0" }
