[package]
name = "bls_sigs_test"
version = "0.1.0"
authors = ["kwantam <kwantam@gmail.com>"]
license = "Apache-2.0"

[dependencies]
bls_sigs_ref-rs = { path = "../" }
pairing = { version = "0.14.8", git = "https://github.com/kwantam/pairing", features = [ "transmutable" ] }
